# Generated by Django 2.2.8 on 2022-08-21 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('dt_start', models.DateTimeField(null=True)),
                ('dt_last_update', models.DateTimeField(null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('avg_value', models.CharField(blank=True, default='', max_length=120, null=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-dt_start'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('BASIC', 'Neutraal'), ('BATH', 'Badkamer'), ('WORK', 'Werkkamer')], max_length=5)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='MessageViewing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField(default=False)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewing', to='analytic_messages.ClimateMessage')),
            ],
            options={
                'db_table': 'message_viewings',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dt_last_update', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('TEMP', 'Temperature'), ('HMD', 'Humidity'), ('CO2', 'CO2 concentration')], max_length=4)),
                ('danger_level', models.IntegerField(choices=[(0, 'safe'), (1, 'warning'), (2, 'danger')])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic_messages.Room')),
            ],
            options={
                'db_table': 'room_measurement',
            },
        ),
        migrations.AddField(
            model_name='climatemessage',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytic_messages.Room'),
        ),
    ]
