# Generated by Django 3.2.7 on 2022-08-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatemessage',
            name='duration',
        ),
        migrations.AddField(
            model_name='climatemessage',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
